# Generated by Django 2.1 on 2018-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('status', models.CharField(choices=[('notchecked', 'Not Checked'), ('warning', 'Warning'), ('error', 'Error'), ('ok', 'OK')], default='notchecked', max_length=15)),
                ('status_text', models.TextField()),
            ],
        ),
    ]
